# Generated by Django 3.1.14 on 2022-03-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220320_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_published',
        ),
    ]
